name: Docker Assignment
on:
  push:
    branches:
      - "master" 

jobs:
  test_build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run : docker build -t b517047/docker-cicd:latest .
      - run : docker login -u b517047 -p ${{secrets.DOCKER_PASS}}
      - run : docker push b517047/docker-cicd:latest